### ISSUE TITLE
Write unit test cases for all the classes

### ISSUE THREAD

**Issue by master-fury** [codezoned/PsipherBackend#32]
write unit test cases for psipher backend

**Comment by NyorJa** [comment]
Hi @master-fury,

Please let me take this issue. What is the target coverage on this?

**Comment by arjunrc143** [comment]
Hi @master-fury 
Added unit tests for password generation feature. Please review

https://github.com/codezoned/PsipherBackend/pull/33

**Comment by NyorJa** [comment]
Hi @master-fury ,

Just a heads up I will be using mockito for this

**Comment by NyorJa** [comment]
hi @master-fury ,
please check [34](https://github.com/codezoned/PsipherBackend/pull/34)

**Comment by NyorJa** [comment]
please add label "hacktoberfest"

**Comment by rahulkrishnan221** [comment]
@NyorJa Nice work. I will review and merge.

**Comment by NyorJa** [comment]
hi @master-fury ,
please close this issue since my changers are merged. Thanks
